name: deploy to devlopment
# mainに対するPRが認証されるときに
on:
  push:
    branches:
      - 'main'
    paths: 
      - 'src/**'
      - .github/workflows/deploy.yml
permissions:
  contents: read
  packages: write
env:
  REGISTRY: ghcr.io
  MANIFEST_REPO: koizumi-yositaka/jwt-tutorial-manifest
  IMAGE_NAME: koizumi-yositaka/jwt-react-app
jobs:
  build-and-push-image:
    outputs:
      IMAGE_NAME: ${{steps.meta.outputs.tags}}
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      issues: write
      packages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
      pages: write  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  #githubが提供するcheckout

      - name: Docker met
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{env.REGISTRY}}/${{github.repository}}


      - name: Log in to Git Hub Container Resistory # GitHUb Crへのログイン
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build and push
        uses: docker/build-push-action@v5
        with: 
          context: .
          push: true
          tags: ${{steps.meta.outputs.tags}}${{github.run_id}}    
          labels: ${{steps.meta.outputs.labels}} 
  update-other-repo:
    runs-on: ubuntu-latest
    needs: [ build-and-push-image]
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.MANIFEST_REPO }}
          token: ${{ secrets.TGT_REPO_PAT }}
          ref: dev
          path: manifest

      - name: Update files
        run: |
          cd manifest
          yq -i "(.spec.template.spec.containers[] | select(.name==\"react-app\")).image=\"${{needs.build-and-push-image.outputs.IMAGE_NAME}}${{github.run_id}}\"" manifest/react/react-deployment.yml

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.TGT_REPO_PAT }}" | gh auth login --with-token

      - name: Create Pull Request from dev to main
        run: |
          gh pr create \
            --repo "${{ env.MANIFEST_REPO }}" \
            --head dev \
            --base main \
            --title "Dev から Main への更新" \
            --body "このプルリクエストは GitHub Actions によって自動的に作成されました。"
